name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: frontierSpaceAlien/MERN-Stack-App@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: "ense701mernapp" #Must be unique in Heroku
          heroku_email: "yxx6616@autuni.ac.nz"
